config = {
    "delay_XP_seconds": 0,
    "level_up_XP": 50,
    "leaderboard_save_interval_seconds": 5,
    "leaderboard_delete_after_seconds": 120,
    "guilds": [473695678690885632, 723199784697200810],
    "fight_song_quotes": [
        "I'm a Ramblin' Wreck from Georgia Tech, and a hell of an engineer",
        "Oh! If I had a daughter, sir, I'd dress her in White and Gold",
        "But if I had a son, sir, He would yell, 'To hell with Georgia!' like his daddy used to do.",
        "Oh, I wish I had a barrel of rum and sugar three thousand pounds,",
        "I'm a ramblin', gamblin', hell of an engineer! ",
        "Like all the jolly good fellows, I drink my whiskey clear.",
        "For I'm a rambling rake of poverty. And the son of a gambolier. ",
        "I'm a son of a, son of a, son of a, son of a, son of a DKE!",
        "He'd yell: 'TO HELL WITH BOULDER!'",
        "I'm a rambling wreck from Golden Tech, a helluva engineer. ",
        "I'm a rambling wreck from Rapid Tech, and a helluva engineer. Hey! ",
        'He would yell "To Hell" with Delaware And yell for O. S. U. ',
        "If I had a daughter, I'd dress her up in green, I'd send her on the campus to coach the Freshman team;",
        "I'm a moral wreck from the Polytech",
        "He fed me all those V-Dogs, and pitchers & pitchers of beer,",
        "Studenter i den gamle stad, ta vare på byens ry!",
        "La'kke byen få ro, men la den få merke det er en studenterby!",
        "Og øl og dram, og øl og dram, og øl og dram, og øl og dram.",
    ],
}
